DATABASE_PATH = 'naec.db'

ALLOWED_SUBJECT_COMBINATIONS = (
    {"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "MATHEMATICS"},
    {"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "HISTORY"},
    {"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "PHYSICS"},
    {"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "BIOLOGY"},
    {"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "CHEMISTRY"},
    {"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "BIOLOGY", "CHEMISTRY"},
    {"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "BIOLOGY", "MATHEMATICS"},
    {"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "BIOLOGY", "PHYSICS"}
)

SUBJECT_POINTS = {
    "GEORGIAN LANGUAGE": 60,
    "FOREIGN LANGUAGE": 70,
    "MATHEMATICS": 51,
    "HISTORY": 60,
    "CHEMISTRY": 63,
    "PHYSICS": 63,
    "BIOLOGY": 70,
}