ALLOWED_SUBJECT_COMBINATIONS = {
    frozenset({"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "MATHEMATICS"}),
    frozenset({"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "HISTORY"}),
    frozenset({"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "PHYSICS"}),
    frozenset({"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "BIOLOGY"}),
    frozenset({"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "CHEMISTRY"}),
    frozenset({"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "BIOLOGY", "CHEMISTRY"}),
    frozenset({"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "BIOLOGY", "MATHEMATICS"}),
    frozenset({"GEORGIAN LANGUAGE", "FOREIGN LANGUAGE", "BIOLOGY", "PHYSICS"}),
}


SUBJECT_POINTS = {
    "GEORGIAN LANGUAGE": 60,
    "FOREIGN LANGUAGE": 70,
    "MATHEMATICS": 51,
    "HISTORY": 60,
    "CHEMISTRY": 63,
    "PHYSICS": 63,
    "BIOLOGY": 70,
}